version: '3'

services:
  # React App
  whatsweather-web:
    extends:
      file: docker-compose.base.yml
      service: nx-app-base
    command: npm run whatsweather-web:dev:docker
    ports:
      - 3002:3002

  # Express App
  whatsweather-api:
    extends:
      file: docker-compose.base.yml
      service: nx-app-base
    command: npm run whatsweather-api:dev:docker
    ports:
      - 3000:3000 # API Entry port
      - 3001:3001 # Server Debugging port
volumes:
  mono-node-modules: null